---
galaxy_info:
  role_name: k3s
  author: Matt2_Chang
  description: Install / uninstall a single-node K3s cluster and deploy kubeconfig
  license: MIT
  min_ansible_version: "2.14"
dependencies: []
